SELECT * FROM PETRESCUE;

SELECT SUM(COST) FROM PETRESCUE;
SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;
SELECT MAX(QUANTITY) from PETRESCUE;
SELECT AVG(COST) FROM PETRESCUE;
SELECT AVG(COST / QUANTITY) FROM PETRESCUE WHERE LCASE(ANIMAL) = 'dog';

SELECT ROUND(COST) FROM PETRESCUE;
SELECT LENGTH(ANIMAL) FROM PETRESCUE;
SELECT UCASE(ANIMAL) FROM PETRESCUE;
SELECT DISTINCT(UCASE(ANIMAL)) FROM PETRESCUE;
SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL) = 'cat';

SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL = 'Cat';
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE) = '05';
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE DAY(RESCUEDATE) = '14';
SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE;
SELECT (CURRENT_DATE - RESCUEDATE) FROM PETRESCUE;